banca:
  dinheiro: 1714.0700000000002
monstros:
  Aranha: 80
  Arcano: 500
  Bandido: 160
  Basilisco: 4700
  Clérigo Corrompido: 1450
  Cobra Selvagem: 260
  Crocodilo: 240
  Dragão: 4650
  Dragão Negro: 5500
  Duende: 90
  Escorpião: 310
  Esqueleto: 100
  Fada: 900
  Fantasma: 300
  Fênix Dourada: 5600
  Gigante: 3000
  Goblin: 150
  Grifo: 4800
  Guerreiro Sombrio: 1400
  Gólem: 5120
  Hidra: 5300
  Leviatã: 4960
  Lobo: 200
  Mago: 400
  Monstro do Lago: 3500
  Ogro: 400
  Orc: 350
  Rato: 50
  Slime: 75
  Spectro: 1300
  Troll Raivoso: 4680
  Zumbi: 140
  Zumbi Gigante: 4700
